# Generated by Django 5.1.2 on 2025-02-07 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField()),
                ('title', models.CharField(default='no title available', max_length=255)),
                ('poster_path', models.CharField(default='null', max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tmdb_id', 'title'), name='unique_user_tmdb_genre'), models.UniqueConstraint(fields=('session_id', 'tmdb_id', 'title'), name='unique_session_tmdb_genre')],
            },
        ),
    ]
