# Generated by Django 5.1.2 on 2025-02-07 09:28

import django.db.models.deletion
import telegram_bot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(validators=[telegram_bot.models.validate_word_limit])),
                ('from_id', models.BigIntegerField()),
                ('tmdb_id', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=10)),
                ('media_content', models.CharField(max_length=50)),
                ('season', models.CharField(blank=True, max_length=400, null=True)),
                ('no_of_files', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20, unique=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True, validators=[telegram_bot.models.validate_word_limit])),
                ('from_id', models.BigIntegerField()),
                ('tmdb_id', models.CharField(max_length=50)),
                ('media_type', models.CharField(max_length=10)),
                ('media_content', models.CharField(blank=True, max_length=50, null=True)),
                ('season', models.CharField(blank=True, max_length=400, null=True)),
                ('available_season', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=300)),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('unique_id', models.ForeignKey(db_column='unique_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='telegram_bot.mediainfo', to_field='unique_id')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=300)),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=10)),
                ('unique_id', models.ForeignKey(db_column='unique_id', on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.sessioninfo', to_field='unique_id')),
            ],
        ),
    ]
