# Generated by Django 5.1.2 on 2025-02-07 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('quality', models.CharField(choices=[('144p', '144p'), ('240p', '240p'), ('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p'), ('2k', '2k'), ('4k', '4k'), ('8k', '8k')], max_length=10)),
                ('site', models.CharField(choices=[('website', 'Website'), ('telegram', 'Telegram'), ('gdrive', 'Google Drive'), ('mega', 'Mega'), ('dropbox', 'Dropbox'), ('4shared', '4shared'), ('zippyshare', 'Zippyshare'), ('other', 'Other File Sharing Service')], max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('audio', models.CharField(blank=True, choices=[('original', 'Original'), ('fandubbed', 'Fandubbed'), ('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('mandarin', 'Mandarin'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('arabic', 'Arabic'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('turkish', 'Turkish'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('catalan', 'Catalan'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('georgian', 'Georgian'), ('hebrew', 'Hebrew'), ('hungarian', 'Hungarian'), ('icelandic', 'Icelandic'), ('italian', 'Italian'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('malay', 'Malay'), ('persian', 'Persian'), ('polish', 'Polish'), ('romanian', 'Romanian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese'), ('filipino', 'Filipino'), ('azerbaijani', 'Azeri')], max_length=20, null=True)),
                ('subtitles', models.CharField(blank=True, choices=[('no_subtitles', 'No Subtitles'), ('english', 'English'), ('hindi', 'Hindi'), ('spanish', 'Spanish'), ('mandarin', 'Mandarin'), ('french', 'French'), ('german', 'German'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('russian', 'Russian'), ('arabic', 'Arabic'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('turkish', 'Turkish'), ('bengali', 'Bengali'), ('bulgarian', 'Bulgarian'), ('catalan', 'Catalan'), ('croatian', 'Croatian'), ('czech', 'Czech'), ('danish', 'Danish'), ('dutch', 'Dutch'), ('estonian', 'Estonian'), ('finnish', 'Finnish'), ('georgian', 'Georgian'), ('hebrew', 'Hebrew'), ('hungarian', 'Hungarian'), ('icelandic', 'Icelandic'), ('italian', 'Italian'), ('latvian', 'Latvian'), ('lithuanian', 'Lithuanian'), ('malay', 'Malay'), ('persian', 'Persian'), ('polish', 'Polish'), ('romanian', 'Romanian'), ('serbian', 'Serbian'), ('slovak', 'Slovak'), ('slovenian', 'Slovenian'), ('swahili', 'Swahili'), ('swedish', 'Swedish'), ('thai', 'Thai'), ('ukrainian', 'Ukrainian'), ('vietnamese', 'Vietnamese'), ('filipino', 'Filipino'), ('azerbaijani', 'Azeri')], max_length=20, null=True)),
                ('decoder', models.CharField(blank=True, choices=[('H.264_8bit', 'H.264 (8-bit)'), ('H.264_10bit', 'H.264 (10-bit)'), ('H.265_8bit', 'H.265 (8-bit)'), ('H.265_10bit', 'H.265 (10-bit)'), ('H.265_12bit', 'H.265 (12-bit)'), ('VP8_8bit', 'VP8 (8-bit)'), ('VP9_8bit', 'VP9 (8-bit)'), ('VP9_10bit', 'VP9 (10-bit)'), ('AV1_8bit', 'AV1 (8-bit)'), ('AV1_10bit', 'AV1 (10-bit)'), ('AV1_12bit', 'AV1 (12-bit)'), ('MPEG-2_8bit', 'MPEG-2 (8-bit)'), ('ProRes_8bit', 'ProRes (8-bit)'), ('ProRes_10bit', 'ProRes (10-bit)'), ('ProRes_12bit', 'ProRes (12-bit)'), ('VP6_8bit', 'VP6 (8-bit)')], max_length=50, null=True)),
                ('format', models.CharField(blank=True, choices=[('WEB-DL', 'WEB-DL'), ('WEBRip', 'WEBRip'), ('HDRip', 'HDRip'), ('BluRay', 'BluRay'), ('BRRip', 'BRRip'), ('HDTV', 'HDTV'), ('HDTVRip', 'HDTVRip'), ('TVRip', 'TVRip'), ('BDRemux', 'BDRemux'), ('DVDRip', 'DVDRip'), ('Telesync', 'Telesync'), ('HDCAM', 'HDCAM'), ('CAM', 'CAM'), ('DVDScr', 'DVDScr'), ('Remux', 'Remux'), ('VOD', 'VOD'), ('PS3', 'PS3')], max_length=20, null=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], max_length=10)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('episode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
